# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: 部署基础包
        run: |
          python -m pip install --upgrade pip
          pip install pipenv pyinstaller


      - name: 部署项目环境
        run: |
          pipenv install

      - name: 编译可执行文件
        run: |
          pyinstaller -F PingStats.py

      - name: 上传artifact
        uses: actions/upload-artifact@v4
        with:
          name: PingStats.exe
          path: dist/PingStats.exe
