# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: 部署基础包
        run: |
          python -m pip install --upgrade pip
          pip install pipenv pyinstaller


      - name: 部署项目环境
        run: |
          pipenv install

      - name: 构建exe
        run: |
          pyinstaller -F PingStats.exe


      - name: 上传artifact
        uses: actions/upload-artifact@v4
        with:
          #          name: PingStats.exe
          path: dist/PingStats.exe
